tunnel: c84d6146-4df6-4822-b2a9-36402a2c49c5
credentials-file: /etc/cloudflared/c84d6146-4df6-4822-b2a9-36402a2c49c5.json

ingress:
  - hostname: vim_relay.hakkadaikon.com
    service: http://127.0.0.1:3000
    originRequest:
      httpHostHeader: vim_relay.hakkadaikon.com
  - service: http_status:404
